-- Modelo físico do Projeto Muambas

CREATE TABLE CLIENTE (
IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(30) NOT NULL,
RG INT (20) NOT NULL,
DATANASCIMENTO DATETIME NOT NULL,
SEXO ENUM('M','F') NOT NULL,
EMAIL VARCHAR(50) UNIQUE,
CPF VARCHAR(15) UNIQUE
);

CREATE TABLE TELEFONE(
IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
TIPO ENUM('RES','COM','CEL') NOT NULL,
NUMERO VARCHAR(10) NOT NULL,
ID_CLIENTE INT,

FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE)

);

CREATE TABLE ENDERECOCLIENTE (
IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
TipoLogradouro VARCHAR(20),
NOME VARCHAR(50) NOT NULL,
NUMERO INTEGER (20) NOT NULL,
CEP INTEGER (10)NOT NULL,
BAIRRO VARCHAR(30) NOT NULL,
ESTADO CHAR(2) NOT NULL,
CIDADE VARCHAR(30) NOT NULL
);

CREATE TABLE CLIENTEEND (
IDCLIENTEEND INTEGER PRIMARY KEY AUTO_INCREMENT,
ID_ENDERECO INT,
ID_CLIENTE INT,
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE (IDCLIENTE),
FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECOCLIENTE (IDENDERECO)
);

CREATE TABLE PRODUTO (
IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(30) NOT NULL,
MODELO VARCHAR(30)NOT NULL,
FABRICANTE VARCHAR(30)NOT NULL,
SERIAL VARCHAR(30) NOT NULL
);

CREATE TABLE CATEGORIA (
IDCATEGORIA INT PRIMARY KEY AUTO_INCREMENT, 
NOME VARCHAR(30) NOT NULL
);

CREATE TABLE CATEGORIAPRODUTO (
IDCATEGORIAPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
ID_PRODUTO INT, 
ID_CATEGORIA INT,
NOME VARCHAR(30) NOT NULL ,

FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO (IDPRODUTO),
FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA (IDCATEGORIA)
);

CREATE TABLE FORNECEDOR (
IDFORNECEDOR INTEGER PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(30)NOT NULL,
CNPJ INTEGER (20)NOT NULL,
VENDEDOR VARCHAR(30)NOT NULL,
TELEFONE VARCHAR(10)NOT NULL,
EMAIL VARCHAR(50) UNIQUE
);

CREATE TABLE PRODUTOFORNECEDOR (
ID_PRODUTOFORNECEDOR INT PRIMARY KEY AUTO_INCREMENT,
ID_PRODUTO INT,
ID_FORNECEDOR INT,

FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO (IDPRODUTO),
FOREIGN KEY(ID_FORNECEDOR) REFERENCES FORNECEDOR (IDFORNECEDOR)
);

CREATE TABLE ENDFORNECEDOR (
IDENDFORNECEDOR INTEGER PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(30)NOT NULL,
CEP INTEGER (10)NOT NULL ,
NUMERO INTEGER (10)NOT NULL,
TIPOLONGRADOURO ENUM ('AV','RUA','ESTR','VIA','BR') NOT NULL,
BAIRRO VARCHAR(30)NOT NULL,
CIDADE VARCHAR(30)NOT NULL,
ESTADO CHAR(2)NOT NULL
);

CREATE TABLE FORNECEDOREND (
IDFORNECEDOREND INT PRIMARY KEY AUTO_INCREMENT,
ID_FORNECEDOR INT,
ID_ENDERECOFORNECEDOR INT,
FOREIGN KEY(ID_FORNECEDOR) REFERENCES FORNECEDOR(IDFORNECEDOR),
FOREIGN KEY(ID_ENDERECOFORNECEDOR) REFERENCES ENDFORNECEDOR(IDENDFORNECEDOR)
);


CREATE TABLE PEDIDO (
IDPEDIDO INT PRIMARY KEY AUTO_INCREMENT,
DATAENTREGA DATETIME,
DATAEMISSAO DATETIME NOT NULL,
VALORTOTAL VARCHAR(10) NOT NULL,
VALORUNITARIO VARCHAR(10) NOT NULL,
FORMAPAGAMENTO VARCHAR(20) NOT NULL,
VALORFRETE VARCHAR(10)NOT NULL
);

CREATE TABLE PRODUTOPEDIDO (
IDPRODUTOPEDIDO INT PRIMARY KEY AUTO_INCREMENT,
ID_PRODUTO INT,
ID_PEDIDO INT,

FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(IDPRODUTO),
FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO(IDPEDIDO)
);

CREATE TABLE VENDA (
IDVENDA INT PRIMARY KEY AUTO_INCREMENT,
VALORTOTAL DECIMAL(20)NOT NULL,
FORMAPAGAMENTO VARCHAR(20) NOT NULL,
ID_CLIENTE INT,

FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE (IDCLIENTE)

);

CREATE TABLE PEDIDOVENDA (
IDPEDIDOVENDA INT PRIMARY KEY AUTO_INCREMENT,
ID_CLIENTE INT,
ID_VENDA INT,
ID_PEDIDO INT,
FOREIGN KEY(ID_VENDA) REFERENCES VENDA (IDVENDA),
FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO (IDPEDIDO),
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE (IDCLIENTE)
);



